/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/d4pi8I16wzG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "../ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "../ui/avatar"
import { Label } from "../ui/label"
import { Input } from "../ui/input"
import { PopoverTrigger, PopoverContent, Popover } from "../ui/popover"
import { Calendar } from "../ui/calendar"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "../ui/select"

export function Availbility() {
  return (
    (<main
      className="grid grid-cols-1 lg:grid-cols-[300px_1fr] gap-8 max-w-6xl mx-auto p-4 lg:p-8">
      <div
        className="bg-white dark:bg-gray-950 rounded-lg shadow-lg overflow-hidden">
        <div
          className="bg-gray-100 dark:bg-gray-800 px-6 py-4 flex items-center justify-between">
          <h2 className="text-lg font-semibold">Upcoming Bookings</h2>
          <Button size="icon" variant="ghost">
            <PlusIcon className="w-5 h-5" />
          </Button>
        </div>
        <div className="p-6 space-y-4">
          <div className="flex items-center gap-4">
            <Avatar>
              <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div>
              <p className="font-medium">John Doe</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Today, 3:00 PM - 4:00 PM</p>
            </div>
            <div className="ml-auto space-x-2">
              <Button size="sm" variant="outline">
                Reschedule
              </Button>
              <Button size="sm" variant="outline">
                Cancel
              </Button>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <Avatar>
              <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div>
              <p className="font-medium">Jane Smith</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Tomorrow, 10:00 AM - 11:00 AM</p>
            </div>
            <div className="ml-auto space-x-2">
              <Button size="sm" variant="outline">
                Reschedule
              </Button>
              <Button size="sm" variant="outline">
                Cancel
              </Button>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <Avatar>
              <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div>
              <p className="font-medium">Michael Johnson</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Friday, 2:00 PM - 3:00 PM</p>
            </div>
            <div className="ml-auto space-x-2">
              <Button size="sm" variant="outline">
                Reschedule
              </Button>
              <Button size="sm" variant="outline">
                Cancel
              </Button>
            </div>
          </div>
        </div>
      </div>
      <div
        className="bg-white dark:bg-gray-950 rounded-lg shadow-lg overflow-hidden">
        <div
          className="bg-gray-100 dark:bg-gray-800 px-6 py-4 flex items-center justify-between">
          <h2 className="text-lg font-semibold">Book an Appointment</h2>
        </div>
        <div className="p-6 space-y-4">
          <form>
            <div className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Enter your name" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" placeholder="Enter your email" type="email" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="date">Date</Label>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button className="w-full flex-col h-auto items-start" variant="outline">
                      <span className="font-semibold uppercase text-[0.65rem]">Select Date</span>
                      <span className="font-normal" />
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="p-0 max-w-[276px]">
                    <Calendar />
                  </PopoverContent>
                </Popover>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="time">Time</Label>
                <Select>
                  <SelectTrigger className="h-auto">
                    <SelectValue
                      placeholder={
                        <div className="flex flex-col items-start">
                          <span className="font-semibold uppercase text-[0.65rem]">Select Time</span>
                          <span className="font-normal">9:00 AM</span>
                        </div>
                      } />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="9:00">9:00 AM</SelectItem>
                    <SelectItem value="10:00">10:00 AM</SelectItem>
                    <SelectItem value="11:00">11:00 AM</SelectItem>
                    <SelectItem value="12:00">12:00 PM</SelectItem>
                    <SelectItem value="13:00">1:00 PM</SelectItem>
                    <SelectItem value="14:00">2:00 PM</SelectItem>
                    <SelectItem value="15:00">3:00 PM</SelectItem>
                    <SelectItem value="16:00">4:00 PM</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="service">Service</Label>
                <Select>
                  <SelectTrigger className="h-auto">
                    <SelectValue
                      placeholder={
                        <div className="flex flex-col items-start">
                          <span className="font-semibold uppercase text-[0.65rem]">Select Service</span>
                          <span className="font-normal">Consultation</span>
                        </div>
                      } />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="consultation">Consultation</SelectItem>
                    <SelectItem value="haircut">Haircut</SelectItem>
                    <SelectItem value="massage">Massage</SelectItem>
                    <SelectItem value="facial">Facial</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <Button className="w-full" size="lg">
                Book Appointment
              </Button>
            </div>
          </form>
        </div>
      </div>
      <div
        className="bg-white dark:bg-gray-950 rounded-lg shadow-lg overflow-hidden">
        <div
          className="bg-gray-100 dark:bg-gray-800 px-6 py-4 flex items-center justify-between">
          <h2 className="text-lg font-semibold">Employee Schedules</h2>
          <Button size="icon" variant="ghost">
            <PlusIcon className="w-5 h-5" />
          </Button>
        </div>
        <div className="p-6 space-y-4">
          <div className="flex items-center gap-4">
            <Avatar>
              <AvatarImage alt="Employee Avatar" src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div>
              <p className="font-medium">John Doe</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Monday - Friday, 9:00 AM - 5:00 PM</p>
            </div>
            <div className="ml-auto space-x-2">
              <Button size="sm" variant="outline">
                Edit
              </Button>
              <Button size="sm" variant="outline">
                Delete
              </Button>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <Avatar>
              <AvatarImage alt="Employee Avatar" src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div>
              <p className="font-medium">Jane Smith</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Tuesday - Saturday, 10:00 AM - 6:00 PM</p>
            </div>
            <div className="ml-auto space-x-2">
              <Button size="sm" variant="outline">
                Edit
              </Button>
              <Button size="sm" variant="outline">
                Delete
              </Button>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <Avatar>
              <AvatarImage alt="Employee Avatar" src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div>
              <p className="font-medium">Michael Johnson</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Wednesday - Sunday, 12:00 PM - 8:00 PM</p>
            </div>
            <div className="ml-auto space-x-2">
              <Button size="sm" variant="outline">
                Edit
              </Button>
              <Button size="sm" variant="outline">
                Delete
              </Button>
            </div>
          </div>
        </div>
      </div>
      <div
        className="bg-white dark:bg-gray-950 rounded-lg shadow-lg overflow-hidden col-span-1 lg:col-span-2">
        <div
          className="bg-gray-100 dark:bg-gray-800 px-6 py-4 flex items-center justify-between">
          <h2 className="text-lg font-semibold">Calendar</h2>
          <div className="flex items-center gap-2">
            <Button size="icon" variant="ghost">
              <ChevronLeftIcon className="w-5 h-5" />
            </Button>
            <span className="text-sm font-medium" />
            <Button size="icon" variant="ghost">
              <ChevronRightIcon className="w-5 h-5" />
            </Button>
          </div>
        </div>
        <div className="p-6">
          <Calendar
            className="[&_td]:w-14 [&_td]:h-14 [&_th]:w-14 [&_th]:h-14 [&>div]:space-x-0 [&>div]:gap-4"
            mode="single" />
        </div>
      </div>
    </main>)
  );
}

function ChevronLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m15 18-6-6 6-6" />
    </svg>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}
