/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5yGfV00ULVq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "../ui/button"
import { Calendar } from "../ui/calendar"
import { Separator } from "../ui/separator"
import { CardContent, Card } from "../ui/card"

export default function BookingCalender() {
  return (
    (<div className="max-w-5xl mx-auto p-4 lg:p-6">
      <div className="flex flex-col gap-8 md:flex-row md:items-start">
        <div className="md:w-1/2">
          <h1 className="text-3xl font-bold mb-4">Book an Appointment</h1>
          <p className="text-gray-500 dark:text-gray-400 mb-8">
            Select an available time slot to book your appointment.
          </p>
          <div className="bg-white dark:bg-gray-950 rounded-lg shadow-lg">
            <Calendar
              className="p-4 [&_td]:w-10 [&_td]:h-10 [&_th]:w-10 [&_[name=day]]:w-10 [&_[name=day]]:h-10 [&>div]:space-x-0 [&>div]:gap-6"
              mode="range"
              numberOfMonths={2}>
              <div className="flex justify-between items-center mb-4">
                <Button size="icon" variant="ghost">
                  <ChevronLeftIcon className="h-4 w-4" />
                </Button>
                <div className="font-medium">April 2023</div>
                <Button size="icon" variant="ghost">
                  <ChevronRightIcon className="h-4 w-4" />
                </Button>
              </div>
            </Calendar>
          </div>
        </div>
        <div className="md:w-1/2">
          <h2 className="text-2xl font-bold mb-4">Selected Appointment</h2>
          <Card>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <div className="font-medium">April 15, 2023</div>
                  <div className="text-gray-500 dark:text-gray-400">10:00 AM - 11:00 AM</div>
                </div>
                <div>
                  <Button size="sm" variant="outline">
                    Change
                  </Button>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <div className="font-medium">Recurring Appointment</div>
                  <div className="text-gray-500 dark:text-gray-400">Every Friday at 10:00 AM</div>
                </div>
                <div>
                  <Button size="sm" variant="outline">
                    Edit
                  </Button>
                </div>
              </div>
              <Separator />
              <div className="flex items-center justify-between">
                <div>
                  <div className="font-medium">Total</div>
                  <div className="text-gray-500 dark:text-gray-400">$99.00</div>
                </div>
                <div>
                  <Button>Book Appointment</Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>)
  );
}

function ChevronLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m15 18-6-6 6-6" />
    </svg>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}
