/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/AaMSw6zeAsw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Calendar } from "../ui/calendar"
import { Label } from "../ui/label"
import { Input } from "../ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "../ui/select"
import { Button } from "../ui/button"
import { PopoverTrigger, PopoverContent, Popover } from "../ui/popover"

export function BookingWidget() {
  return (
    (<main
      className="flex flex-col items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-900 p-4">
      <div
        className="max-w-3xl w-full bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
        <header className="bg-gray-900 dark:bg-gray-950 py-4 px-6">
          <h1 className="text-white text-2xl font-bold">Book an Appointment</h1>
        </header>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 p-8">
          <div>
            <h2 className="text-gray-900 dark:text-gray-100 text-xl font-semibold mb-4">Select a Date</h2>
            <Calendar className="w-full rounded-lg shadow-lg" mode="single" />
          </div>
          <div>
            <h2 className="text-gray-900 dark:text-gray-100 text-xl font-semibold mb-4">Schedule an Appointment</h2>
            <form className="space-y-4">
              <div>
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Enter your name" />
              </div>
              <div>
                <Label htmlFor="email">Email</Label>
                <Input id="email" placeholder="Enter your email" type="email" />
              </div>
              <div>
                <Label htmlFor="service">Service</Label>
                <Select id="service">
                  <SelectTrigger>
                    <SelectValue placeholder="Select a service" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="gardening">Gardening</SelectItem>
                    <SelectItem value="plumbing">Plumbing</SelectItem>
                    <SelectItem value="pool-cleaning">Pool Cleaning</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label htmlFor="time">Time</Label>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button className="w-full justify-start" variant="outline">
                      <ClockIcon className="mr-2" />
                      Select a time
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="p-0 w-64">
                    <div className="grid grid-cols-3 gap-2 p-4">
                      <Button size="sm" variant="outline">
                        9:00 AM
                      </Button>
                      <Button size="sm" variant="outline">
                        10:00 AM
                      </Button>
                      <Button size="sm" variant="outline">
                        11:00 AM
                      </Button>
                      <Button size="sm" variant="outline">
                        1:00 PM
                      </Button>
                      <Button size="sm" variant="outline">
                        2:00 PM
                      </Button>
                      <Button size="sm" variant="outline">
                        3:00 PM
                      </Button>
                    </div>
                  </PopoverContent>
                </Popover>
              </div>
              <Button className="w-full" type="submit">
                Book Appointment
              </Button>
            </form>
          </div>
        </div>
      </div>
    </main>)
  );
}

function ClockIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>)
  );
}
