/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/y8eIbOV9A3l
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Link } from '@chakra-ui/react'
import { Button } from "../ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "../ui/dropdown-menu"
import { Label } from "../ui/label"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "../ui/select"
import { PopoverTrigger, PopoverContent, Popover } from "../ui/popover"
import { Calendar } from "../ui/calendar"
import { Input } from "../ui/input"
import { Textarea } from "../ui/textarea"

export default function BookingCalender5() {
  return (
    (

      <main className="flex-1 py-8">
        <div
          className="container mx-auto grid grid-cols-1 gap-8 md:grid-cols-[1fr_300px]">
          <div className="rounded-lg bg-white p-6 shadow-sm dark:bg-gray-900">
            <div className="mb-6 flex items-center justify-between">
              <h1 className="text-2xl font-semibold">Schedule an Appointment</h1>
              <div className="flex items-center gap-4">
                <Button variant="outline">
                  <CalendarIcon className="h-4 w-4" />
                  <span>View Calendar</span>
                </Button>
                <Button>
                  <PlusIcon className="h-4 w-4" />
                  <span>New Appointment</span>
                </Button>
              </div>
            </div>
            <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
              <div>
                <Label htmlFor="service">Service</Label>
                <Select id="service">
                  <SelectTrigger>
                    <SelectValue placeholder="Select a service" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="gardening">Gardening</SelectItem>
                    <SelectItem value="plumbing">Plumbing</SelectItem>
                    <SelectItem value="pool-cleaning">Pool Cleaning</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label htmlFor="date">Date</Label>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button className="w-full" variant="outline">
                      <CalendarIcon className="h-4 w-4" />
                      <span>Select a date</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="p-0">
                    <Calendar />
                  </PopoverContent>
                </Popover>
              </div>
              <div>
                <Label htmlFor="time">Time</Label>
                <Select id="time">
                  <SelectTrigger>
                    <SelectValue placeholder="Select a time" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="9:00">9:00 AM</SelectItem>
                    <SelectItem value="10:00">10:00 AM</SelectItem>
                    <SelectItem value="11:00">11:00 AM</SelectItem>
                    <SelectItem value="12:00">12:00 PM</SelectItem>
                    <SelectItem value="13:00">1:00 PM</SelectItem>
                    <SelectItem value="14:00">2:00 PM</SelectItem>
                    <SelectItem value="15:00">3:00 PM</SelectItem>
                    <SelectItem value="16:00">4:00 PM</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label htmlFor="duration">Duration</Label>
                <Select id="duration">
                  <SelectTrigger>
                    <SelectValue placeholder="Select a duration" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="30">30 minutes</SelectItem>
                    <SelectItem value="60">1 hour</SelectItem>
                    <SelectItem value="90">1.5 hours</SelectItem>
                    <SelectItem value="120">2 hours</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Enter your name" />
              </div>
              <div>
                <Label htmlFor="email">Email</Label>
                <Input id="email" placeholder="Enter your email" type="email" />
              </div>
              <div>
                <Label htmlFor="phone">Phone</Label>
                <Input id="phone" placeholder="Enter your phone number" />
              </div>
              <div>
                <Label htmlFor="notes">Notes</Label>
                <Textarea id="notes" placeholder="Enter any additional notes" />
              </div>
            </div>
            <div className="mt-6 flex justify-end gap-4">
              <Button variant="outline">Cancel</Button>
              <Button>Book Appointment</Button>
            </div>
          </div>
          <div className="rounded-lg bg-white p-6 shadow-sm dark:bg-gray-900">
            <h2 className="mb-4 text-xl font-semibold">Upcoming Appointments</h2>
            <div className="grid gap-4">
              <div
                className="flex items-center justify-between rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
                <div className="flex items-center gap-4">
                  <div
                    className="flex h-10 w-10 items-center justify-center rounded-full bg-primary text-white">
                    <CalendarIcon className="h-5 w-5" />
                  </div>
                  <div>
                    <p className="font-medium">Gardening Service</p>
                    <p className="text-sm text-gray-500 dark:text-gray-400">May 15, 2023 at 10:00 AM</p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <Button size="sm" variant="outline">
                    <PencilIcon className="h-4 w-4" />
                    <span>Reschedule</span>
                  </Button>
                  <Button className="text-red-500" size="sm" variant="outline">
                    <TrashIcon className="h-4 w-4" />
                    <span>Cancel</span>
                  </Button>
                </div>
              </div>
              <div
                className="flex items-center justify-between rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
                <div className="flex items-center gap-4">
                  <div
                    className="flex h-10 w-10 items-center justify-center rounded-full bg-primary text-white">
                    <CalendarIcon className="h-5 w-5" />
                  </div>
                  <div>
                    <p className="font-medium">Plumbing Service</p>
                    <p className="text-sm text-gray-500 dark:text-gray-400">May 20, 2023 at 2:00 PM</p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <Button size="sm" variant="outline">
                    <PencilIcon className="h-4 w-4" />
                    <span>Reschedule</span>
                  </Button>
                  <Button className="text-red-500" size="sm" variant="outline">
                    <TrashIcon className="h-4 w-4" />
                    <span>Cancel</span>
                  </Button>
                </div>
              </div>
              <div
                className="flex items-center justify-between rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
                <div className="flex items-center gap-4">
                  <div
                    className="flex h-10 w-10 items-center justify-center rounded-full bg-primary text-white">
                    <CalendarIcon className="h-5 w-5" />
                  </div>
                  <div>
                    <p className="font-medium">Pool Cleaning</p>
                    <p className="text-sm text-gray-500 dark:text-gray-400">June 1, 2023 at 9:00 AM</p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <Button size="sm" variant="outline">
                    <PencilIcon className="h-4 w-4" />
                    <span>Reschedule</span>
                  </Button>
                  <Button className="text-red-500" size="sm" variant="outline">
                    <TrashIcon className="h-4 w-4" />
                    <span>Cancel</span>
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
     )
  );
}

function CalendarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>)
  );
}


function PencilIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
      <path d="m15 5 4 4" />
    </svg>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}


function TrashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>)
  );
}
