/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Jmj5mgjnOhl
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "../ui/button"
import { Calendar } from "../ui/calendar"
import { Label } from "../ui/label"
import { Input } from "../ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "../ui/select"
import { PopoverTrigger, PopoverContent, Popover } from "../ui/popover"
import { CardTitle, CardHeader, CardContent, Card } from "../ui/card"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "../ui/table"
import { Badge } from "../ui/badge"

export default function BookingCalender4() {
  return (
    (<div className="flex flex-col h-screen">
      <header
        className="bg-gray-900 text-white py-4 px-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <CalendarIcon className="w-6 h-6" />
          <h1 className="text-2xl font-bold">Booking Solution</h1>
        </div>
        <div className="flex items-center gap-4">
          <Button variant="outline">Sign In</Button>
          <Button>Sign Up</Button>
        </div>
      </header>
      <main className="flex-1 grid grid-cols-1 md:grid-cols-2 gap-8 p-8">
        <section>
          <h2 className="text-2xl font-bold mb-4">Calendar</h2>
          <div className="bg-white rounded-lg shadow-lg p-6">
            <Calendar mode="single" />
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-4">Book an Appointment</h2>
          <div className="bg-white rounded-lg shadow-lg p-6">
            <form className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Enter your name" required />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" placeholder="Enter your email" required type="email" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="service">Service</Label>
                <Select id="service" required>
                  <SelectTrigger>
                    <SelectValue placeholder="Select a service" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="haircut">Haircut</SelectItem>
                    <SelectItem value="massage">Massage</SelectItem>
                    <SelectItem value="nails">Nails</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="date">Date</Label>
                <Popover>
                  <PopoverTrigger asChild>
                    <Input id="date" placeholder="Select a date" readOnly />
                  </PopoverTrigger>
                  <PopoverContent className="p-0">
                    <Calendar mode="single" />
                  </PopoverContent>
                </Popover>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="time">Time</Label>
                <Select id="time" required>
                  <SelectTrigger>
                    <SelectValue placeholder="Select a time" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="9:00">9:00 AM</SelectItem>
                    <SelectItem value="10:00">10:00 AM</SelectItem>
                    <SelectItem value="11:00">11:00 AM</SelectItem>
                    <SelectItem value="12:00">12:00 PM</SelectItem>
                    <SelectItem value="13:00">1:00 PM</SelectItem>
                    <SelectItem value="14:00">2:00 PM</SelectItem>
                    <SelectItem value="15:00">3:00 PM</SelectItem>
                    <SelectItem value="16:00">4:00 PM</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <Button className="justify-self-end" type="submit">
                Book Appointment
              </Button>
            </form>
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-4">Dashboard</h2>
          <div className="bg-white rounded-lg shadow-lg p-6 grid gap-4">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <Card>
                <CardHeader className="flex items-center justify-between">
                  <CardTitle>Upcoming Appointments</CardTitle>
                  <CalendarIcon className="w-6 h-6 text-gray-500" />
                </CardHeader>
                <CardContent className="text-4xl font-bold">12</CardContent>
              </Card>
              <Card>
                <CardHeader className="flex items-center justify-between">
                  <CardTitle>Customers</CardTitle>
                  <UsersIcon className="w-6 h-6 text-gray-500" />
                </CardHeader>
                <CardContent className="text-4xl font-bold">342</CardContent>
              </Card>
              <Card>
                <CardHeader className="flex items-center justify-between">
                  <CardTitle>Revenue</CardTitle>
                  <DollarSignIcon className="w-6 h-6 text-gray-500" />
                </CardHeader>
                <CardContent className="text-4xl font-bold">$8,450</CardContent>
              </Card>
              <Card>
                <CardHeader className="flex items-center justify-between">
                  <CardTitle>Availability</CardTitle>
                  <ClockIcon className="w-6 h-6 text-gray-500" />
                </CardHeader>
                <CardContent className="text-4xl font-bold">92%</CardContent>
              </Card>
            </div>
            <div>
              <h3 className="text-xl font-bold mb-4">Upcoming Appointments</h3>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Customer</TableHead>
                    <TableHead>Service</TableHead>
                    <TableHead>Date</TableHead>
                    <TableHead>Time</TableHead>
                    <TableHead>Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>John Doe</TableCell>
                    <TableCell>Haircut</TableCell>
                    <TableCell>2023-05-18</TableCell>
                    <TableCell>10:00 AM</TableCell>
                    <TableCell>
                      <Badge variant="success">Confirmed</Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Jane Smith</TableCell>
                    <TableCell>Massage</TableCell>
                    <TableCell>2023-05-19</TableCell>
                    <TableCell>2:00 PM</TableCell>
                    <TableCell>
                      <Badge variant="warning">Pending</Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>Bob Johnson</TableCell>
                    <TableCell>Nails</TableCell>
                    <TableCell>2023-05-20</TableCell>
                    <TableCell>4:30 PM</TableCell>
                    <TableCell>
                      <Badge variant="success">Confirmed</Badge>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-gray-900 text-white py-4 px-6 text-center">
        © 2023 Booking Solution. All rights reserved.
      </footer>
    </div>)
  );
}

function CalendarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>)
  );
}


function ClockIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>)
  );
}


function DollarSignIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
    </svg>)
  );
}


function UsersIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>)
  );
}
